[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[include]
files = /etc/supervisor/conf.d/*.conf


; Queue workers managed by Horizon — see supervisor.conf + config/horizon.php
